task: Cifar10
synthesizer: Pattern

random_seed: 42
batch_size: 64
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 220
poison_epoch: 0
poison_epoch_stop: 220
save_on_epochs: [] # [30, 50, 80, 100, 120, 150, 170, 200]
optimizer: SGD
log_interval: 100

poisoning_proportion: 0.5
backdoor_label: 8

# resume_model:
# resume_model: /cifar_pretrain/model_last.pt.tar.epoch_200

save_model: False
log: True

transform_train: True

fl: True
fl_no_models: 5
fl_local_epochs: 1
# fl_poison_epochs: 15
fl_poison_epochs: 5
fl_total_participants: 10
fl_eta: 1 # 0.8
fl_sample_dirichlet: True
fl_dirichlet_alpha: 0.9

fl_number_of_adversaries: 2
fl_weight_scale: 1
fl_adv_group_size: 2
# fl_single_epoch_attack: 200

attack: ModelReplace
defense: 'FedAvg'
fl_num_neurons: 5
noise_mask_alpha: 0 # 0.5
lagrange_step: 0.1